# Generated by Django 5.2.16 on 2026-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier the frontend looks up, e.g. 'home-hero-heading'.", unique=True)),
                ('label', models.CharField(help_text='What this block is, for admin users.', max_length=120)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='content/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
