# Generated by Django 5.2.16 on 2026-07-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('maps_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL for this branch (Share → Embed a map).')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('medicines', 'Medicines'), ('supplements', 'Supplements'), ('first-aid', 'First Aid'), ('personal-care', 'Personal Care'), ('mother-baby', 'Mother & Baby'), ('devices', 'Medical Devices')], max_length=20)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in UGX', max_digits=12)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in UGX', max_digits=12)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'ordering': ['category__ordering', 'name'],
            },
        ),
    ]
